kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: prime-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zones: eu-west-3a, eu-west-3b
  iopsPerGB: "10" 
  fsType: ext4